#!/usr/bin/env bash
# Shows information about ssubdomains

domain ()  {
    dig "$1" | grep -A1 'ANSWER SECTION:' | sed -r "s/$1./$2/g" | awk -F" " ' NR==2{ print "The subdomain " $1 " is a " $4 " record and points to " $5 }'
}

if [ "$# -eq 1 ]
then
    domain "$1" "www"
    domain "$1" "lb-01"
    domain "$1" "web-01"
    domain "$1" "web-02"
else
    domain "$1" "$2"
fi
