#!/usr/bin/env bash
Shows information about ssubdomains

domain ()  {
	info = $(dig "$2"."$1" | grep -A1 "ANSWER SECTION:' | tail -1)
	echo "$2 $info" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}
}

if [ "$# -eq 1 ]
then
    domain "$1" "www"
    domain "$1" "lb-01"
    domain "$1" "web-01"
    domain "$1" "web-02"
else
    domain "$1" "$2"
fi
