#!/usr/bin/env bash
# Co nfigures a new Nginx server

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.html
string_replace="server_name_;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent:"
sudo sed -i "s/server_name_;/$string_replace/" /etc/nginx/sites-enabled/default
sudo service nginx restart
