#!/usr/bin/env bash
#Prints best school with while loop having hi as the ninth number
count=1
while [ $count -le 10 ]
do
	echo "Best School"
	if [ $count == 9 ]
	then
		echo "Hi"
	fi
	(( count++ ))
done
