#!/usr/bin/env bash
# RUns user nginx
sudo pkill apache2
sudo chmod 644 /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/' /etc/nginx/sites-enabled/default
sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.conf
sudo -u nginx service nginx start
